"""add unique constraint to candles

Revision ID: 3cbe9cb1ca25
Revises: 7654cf03860b
Create Date: 2026-02-26 15:27:28.024010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbe9cb1ca25'
down_revision: Union[str, Sequence[str], None] = '7654cf03860b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_candle_asset_time_interval', 'candles', ['asset_id', 'time', 'interval'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candle_asset_time_interval', 'candles', type_='unique')
    # ### end Alembic commands ###
