"""add_tp_sl_order_ids_to_trades

Revision ID: 855e365d6518
Revises: c5d6e7f8a9b0
Create Date: 2026-03-10 09:54:05.321344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855e365d6518'
down_revision: Union[str, Sequence[str], None] = 'c5d6e7f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('tp_order_id', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('sl_stop_order_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'sl_stop_order_id')
    op.drop_column('trades', 'tp_order_id')
    # ### end Alembic commands ###
